// THIS FILE WAS GENERATED BY A TOOL, DO NOT EDIT!

package main

import (
    "github.com/lxn/walk"
)

type myDialogUI struct {
    uploadBtn *walk.PushButton
    fileLe    *walk.LineEdit
    uploadGb  *walk.GroupBox
    logGb     *walk.GroupBox
    browseBtn *walk.PushButton
}

func (w *MyDialog) init(owner walk.Form) (err error) {
    w.SetMinimizeBox(true)
    w.SetMaximizeBox(false)
    w.SetFixedSize(true)

    if w.Dialog, err = walk.NewDialog(owner); err != nil {
        return err
    }

    succeeded := false
    defer func() {
        if !succeeded {
            w.Dispose()
        }
    }()

    var font *walk.Font
    if font == nil {
        font = nil
    }

    w.SetName("windows")
    if err := w.SetClientSize(walk.Size{376, 287}); err != nil {
        return err
    }
    if err := w.SetTitle(`iMan-测试程序`); err != nil {
        return err
    }

    if w.ui.uploadGb, err = walk.NewGroupBox(w); err != nil {
        return err
    }

    if err := w.ui.uploadGb.SetBounds(walk.Rectangle{3, 7, 368, 138}); err != nil {
        return err
    }

    w.ui.uploadGb.SetTitle("升级包上传")

    // fileLe
    if w.ui.fileLe, err = walk.NewLineEdit(w.ui.uploadGb); err != nil {
        return err
    }

    if err := w.ui.fileLe.SetBounds(walk.Rectangle{7, 33, 255, 27}); err != nil {
        return err
    }

    // uploadFileBt
    if w.ui.browseBtn, err = walk.NewPushButton(w.ui.uploadGb); err != nil {
        return err
    }

    w.ui.browseBtn.SetName("uploadFileBt")
    if err := w.ui.browseBtn.SetBounds(walk.Rectangle{285, 34, 57, 27}); err != nil {
        return err
    }

    if err := w.ui.browseBtn.SetText(`浏览`); err != nil {
        return err
    }

    // uploadFileBt
    if w.ui.uploadBtn, err = walk.NewPushButton(w.ui.uploadGb); err != nil {
        return err
    }

    w.ui.uploadBtn.SetName("uploadFileBt")
    if err := w.ui.uploadBtn.SetBounds(walk.Rectangle{151, 92, 57, 27}); err != nil {
        return err
    }

    if err := w.ui.uploadBtn.SetText(`上传`); err != nil {
        return err
    }

    if w.ui.logGb, err = walk.NewGroupBox(w); err != nil {
        return err
    }

    if err := w.ui.logGb.SetBounds(walk.Rectangle{3, 153, 368, 127}); err != nil {
        return err
    }

    w.ui.logGb.SetTitle("日志")

    succeeded = true

    return nil
}
